[versions]
fabric-loader = "0.19.3"
fabric-loom = "1.17-SNAPSHOT"
minecraft = "1.8.9"
kotlin = "2.4.0"
lenis = "0.1.4"
joml = "1.10.8"
imgui = "1.89.0"
zstd = "1.5.7-16"
javacpp = "1.5.14"
javacpp-ffmpeg = "8.1.2-1.5.14"
osl = "0.17.1"
devauth = "1.2.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
lenis = { module = "pl.tomgirl:lenis", version.ref = "lenis" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
joml = { module = "org.joml:joml", version.ref = "joml" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }
javacpp-core = { module = "org.bytedeco:javacpp", version.ref = "javacpp" }
javacpp-ffmpeg = { module = "org.bytedeco:ffmpeg", version.ref = "javacpp-ffmpeg" }

imgui-binding = { module = "io.github.spair:imgui-java-binding", version.ref = "imgui" }
imgui-natives-windows = { module = "io.github.spair:imgui-java-natives-windows", version.ref = "imgui" }
imgui-natives-linux = { module = "io.github.spair:imgui-java-natives-linux", version.ref = "imgui" }
imgui-natives-macos = { module = "io.github.spair:imgui-java-natives-macos", version.ref = "imgui" }

devauth-fabric = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
ploceus = { id = "ploceus", version.ref = "fabric-loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
