package gg.sona.recast.editor.imgui


enum class Icon {
    PLAY, PAUSE, STOP, STEP_BACK, STEP_FORWARD, SKIP_START, SKIP_END, REWIND, FAST_FORWARD,
    RECORD, LOOP, KEYFRAME, KEYFRAME_ADD, MARKER, MARK_IN, MARK_OUT, CAMERA, EYE, EYE_OFF,
    LOCK, UNLOCK, PLUS, MINUS, CLOSE, CHEVRON_DOWN, CHEVRON_UP, CHEVRON_RIGHT, SEARCH, SETTINGS, FULLSCREEN,
    ZOOM_IN, ZOOM_OUT, FIT, MAGNET, FOLLOW, TRASH, EXPORT, FOLDER, FILM, USER, LINK, CHECK, WARNING, INFO,
    SAVE, UNDO, REDO, COPY, PASTE, SCISSORS, ARROW_RIGHT, ARROW_LEFT, CLOCK, SUN, GAUGE, VOLUME, LAYERS, PATH, TARGET, ORBIT,
    PERSON, GRID, MORE, REFRESH, COMPRESS, HOME, EDIT, TAG, DOT, IMAGE, COMMAND, SLIDERS, PIN, BOOKMARK,
    TOOL_VIEW, TOOL_MOVE, TOOL_ROTATE, TOOL_SCALE, GLOBE, CUBE, LIST, CHEVRON_LEFT, WAVE, APERTURE, SIDEBAR, MONITOR, SNOWFLAKE, ARROW_UP, ARROW_DOWN, CIRCLE,
    GRAPH, AUTO_KEY,
}
